version: '3.1'

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:14.7
    container_name: postgres
    # 5432로 포워딩 할 경우 host os 에 설치된 postgre와 겹칠 수 있으므로 host에 설치된 postgre를 내려야함
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    restart: always
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    restart: always
    networks:
      - app-network

  nestjs:
    image: ghcr.io/ldywinner/ssu-gang-pyeong-ver2:latest
    container_name: nestjs
    ports:
      - '3000:3000'
    restart: always
    networks:
      - app-network
