FROM node:18.14.2 AS builder
RUN mkdir -p /app
WORKDIR /app
ADD . .

RUN npm uninstall bcrypt --force
RUN npm install bcrypt --force
RUN npm install --force

WORKDIR /app/apps/api-server
RUN npm run build

ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}
ARG DB_HOST
ENV DB_HOST ${DB_HOST}
ARG DB_PORT
ENV DB_PORT ${DB_PORT}
ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}
ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}
ARG DB_NAME
ENV DB_NAME ${DB_NAME}
ARG SENTRY_DSN
ENV SENTRY_DSN ${SENTRY_DSN}
ARG SLACK_WEBHOOK_URL
ENV SLACK_WEBHOOK_URL ${SLACK_WEBHOOK_URL}
ARG NODEMAIL_USER
ENV NODEMAIL_USER ${NODEMAIL_USER}
ARG NODEMAIL_PASS
ENV NODEMAIL_PASS ${NODEMAIL_PASS}
ARG JWT_SECRET
ENV JWT_SECRET ${JWT_SECRET}
ARG JWT_LIFETIME
ENV JWT_LIFETIME ${JWT_LIFETIME}
ARG JWT_REFRESH_LIFETIME
ENV JWT_REFRESH_LIFETIME ${JWT_REFRESH_LIFETIME}

CMD npm run typeorm migration:run;npm run start:prod