name: CI/CD Docker

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ghcr.io/ldywinner/ssu-gang-pyeong-ver2
  VERSION: ${{ github.sha }}
  NAME: cicd_test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ldywinner
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          build-args: |
            "STAGE=${{ secrets.STAGE }}"
            "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}"
            "SENTRY_DSN=${{ secrets.SENTRY_DSN }}"
            "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}"
            "EMAIL_USER=${{ secrets.EMAIL_USER }}"
            "EMAIL_PASS=${{ secrets.EMAIL_PASS }}"
            "JWT_SECRET=${{ secrets.JWT_SECRET }}"
            "SWAGGER_USER=${{ secrets.SWAGGER_USER }}"
            "SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }}"
            "REDIS_HOST=${{ secrets.REDIS_HOST }}"
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ldywinner
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker run
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
